Increase toast max-width
This makes it big enough to fit the compiler error message

    IndentationError: unindent doesn't match any outer indent level

If we still have problems with overflow we should probably look at
ways to wrap <pre> text instead of making this wider.