build(deps): bump @types/react from 18.2.21 to 18.2.37 (#2087)
* build(deps): bump @types/react from 18.2.21 to 18.2.37

Bumps [@types/react](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/HEAD/types/react) from 18.2.21 to 18.2.37.
- [Release notes](https://github.com/DefinitelyTyped/DefinitelyTyped/releases)
- [Commits](https://github.com/DefinitelyTyped/DefinitelyTyped/commits/HEAD/types/react)

---
updated-dependencies:
- dependency-name: "@types/react"
  dependency-type: direct:production
  update-type: version-update:semver-patch
...

Signed-off-by: dependabot[bot] <support@github.com>

* yarn: update react-splitter-layout

* fix type errors for react-splitter-layout

Upgrading to `@types/react` > 18.2.21 causes the following errors:

```
src/app/App.tsx:202:22 - error TS2786: 'SplitterLayout' cannot be used as a JSX component.
  Its instance type 'SplitterLayout' is not a valid JSX element.
    The types returned by 'render()' are incompatible between these types.
      Type 'import("/home/david/work/pybricks/pybricks-code/node_modules/@types/react-dom/node_modules/@types/react/ts5.0/index").ReactNode' is not assignable to type 'React.ReactNode'.
        Type 'ReactElement<any, string | JSXElementConstructor<any>>' is not assignable to type 'ReactNode'.
          Property 'children' is missing in type 'ReactElement<any, string | JSXElementConstructor<any>>' but required in type 'ReactPortal'.

202                     <SplitterLayout
                         ~~~~~~~~~~~~~~

  node_modules/@types/react/ts5.0/index.d.ts:175:9
    175         children: ReactNode;
                ~~~~~~~~
    'children' is declared here.

src/app/App.tsx:212:26 - error TS2786: 'SplitterLayout' cannot be used as a JSX component.
  Its instance type 'SplitterLayout' is not a valid JSX element.

212                         <SplitterLayout
                             ~~~~~~~~~~~~~~

Found 2 errors in the same file, starting at: src/app/App.tsx:202
```

https://arethetypeswrong.github.io/?p=react-splitter-layout%404.0.0

provided the hint that we need `export =` instead of `export default`.

---------

Signed-off-by: dependabot[bot] <support@github.com>
Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>
Co-authored-by: David Lechner <david@pybricks.com>